Tweak XCM slides for PBA4
Polkadot-Blockchain-Academy/pba-content pull request #936
Opened 2024-01-18 09:14 UTC by franciscoaguirre

- Move some content from lesson 1 to lesson 2 since it was too big
- Improve XCVM execution diagrams (lecture 2)
- Simplify pallet-xcm slides (lecture 3)
- Make configuration slides less repetitive and add attack scenarios with barriers to fix them (lecture 4)

2024-01-18 14:19 UTC, wirednkod requested changes

2024-01-18 14:19 UTC, wirednkod commented on syllabus/8-XCM/2-XCVM/XCVM_slides.md
> +<img rounded style="width: 500px;" src="../../../assets/img/8-XCM/teleport.png" />
Please move the images inside the 8-XCM directory, and pick them from there (delete the old ones).
After that move the above should be:
```suggestion
<img rounded style="width: 500px;" src="../img/8-XCM/teleport.png" />
```

2024-01-18 14:19 UTC, wirednkod commented on syllabus/8-XCM/2-XCVM/XCVM_slides.md
> +<img rounded style="width: 400px;" src="../../../assets/img/8-XCM/reserve-tx.png" />
Please move the images inside the 8-XCM directory, and pick them from there (delete the old ones).
After that move the above should be:
```suggestion
<img rounded style="width: 500px;" src="../img/8-XCM/reserve-tx.png" />
```

2024-01-18 15:24 UTC, wirednkod submitted a review, later dismissed
link-wise, code-wise and assets-wise that looks good.
@KiChjang will have to check the content I guess

2024-01-23 15:36 UTC, KiChjang commented on syllabus/8-XCM/2-XCVM/XCVM_slides.md
> +An instruction used to get assets from an account into the holding register.
```suggestion
An instruction used to get assets from an account and put it into the holding register.
```

2024-01-23 15:38 UTC, KiChjang commented on syllabus/8-XCM/2-XCVM/XCVM_slides.md
> +Here we have a very simple program, which if executed locally would result in a regular asset transfer.
```suggestion
Here we have a very simple program, which if executed locally would result in a regular asset transfer within a single consensus system.
```

2024-01-23 15:38 UTC, KiChjang commented on syllabus/8-XCM/2-XCVM/XCVM_slides.md
> +TODO: Move elsewhere.
Move elsewhere?

2024-01-26 13:06 UTC, wirednkod approved these changes

2024-01-27 10:09 UTC, KiChjang approved these changes

2024-01-27 10:09 UTC, merged