Blockchain Module: New Readme Format for Singapore
Polkadot-Blockchain-Academy/pba-content pull request #989
Opened 2024-04-09 16:03 UTC by JoshOrndorff

This PR revises the module 3 content in the direction requested in #982 but is made directly against main to better preserve the history of the files.

If this pr is accepted it can also be merged into #982 for anyone following that branch.

Tasklist:
- [x] Change format of readme
- [x] Change file names for lessons
- [x] Write learning outcomes 
- [ ] Move start a blockchain info to dedicated repo
- [ ] prune unused images

2024-04-09 16:21 UTC, wirednkod requested changes
Please reopen this PR against `2024-singapore` repository instead of `main` - as track of changes are kept there.

2024-04-09 17:09 UTC, JoshOrndorff commented
The CI is catching broken links but they are not from this PR, so I recommend merging once it is reviewed positively.

2024-04-11 19:52 UTC, JoshOrndorff commented on syllabus/3-Blockchain/README.md
It is not a dedicated lesson. I will introduce what smart contracts are and cover their history in the first two lessons. Then the topic of contracts will come up several times throughout the module organically as it usually does.

2024-04-11 19:59 UTC, wirednkod commented on syllabus/3-Blockchain/README.md
Sounds great. Thank you Joshy

2024-04-17 07:14 UTC, merged